/*
{
"notebooksnap": {
        "cell_name": "Create Example DIM_COLUMN Table (snowflake)",
        "connection": "snowflake-demo",
        "pattern": "Execute SQL"
    }
}
*/
CREATE TABLE IF NOT EXISTS /*${snowflake_Schema}*/"STG"/**/.DIM_COLUMN (
	COLUMN_SK NUMBER(38,0) autoincrement,
	TABLE_CATALOG VARCHAR(255),
	TABLE_SCHEMA VARCHAR(255),
	TABLE_NAME VARCHAR(255),
	COLUMN_NAME VARCHAR(255),
	ORDINAL_POSITION NUMBER(38,0),
	IS_NULLABLE VARCHAR(4),
	DATA_TYPE VARCHAR(255),
	CHARACTER_MAXIMUM_LENGTH NUMBER(38,0),
	PRIMARY_KEY VARCHAR(4),
	ROW_DATA_SOURCE VARCHAR(16),
	ROW_IS_CURRENT VARCHAR(4),
	ROW_EFFECTIVE_DATE DATE,
	ROW_EXPIRATION_DATE DATE,
	ROW_INSERT_DATE DATE,
	ROW_UPDATE_DATE DATE
);